//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto.Modelos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Campeonato
    {
        public Campeonato()
        {
            this.Equipos_x_Campeonato = new HashSet<Equipos_x_Campeonato>();
        }
    
        public int id { get; set; }
        public Nullable<System.DateTime> fec_inicio { get; set; }
        public Nullable<System.DateTime> fec_fin { get; set; }
        public int cant_equipos { get; set; }
        public int id_dedicado { get; set; }
    
        public virtual Persona Persona { get; set; }
        public virtual ICollection<Equipos_x_Campeonato> Equipos_x_Campeonato { get; set; }
    }
}
