//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto.Modelos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Equipos_x_Campeonato
    {
        public int id { get; set; }
        public int id_equipo { get; set; }
        public int id_campeonato { get; set; }
    
        public virtual Campeonato Campeonato { get; set; }
        public virtual Equipos Equipos { get; set; }
    }
}
