//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto.Modelos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Equipos
    {
        public Equipos()
        {
            this.Equipos_x_Campeonato = new HashSet<Equipos_x_Campeonato>();
            this.Jugadores = new HashSet<Jugadore>();
            this.Partidos = new HashSet<Partido>();
            this.Partidos1 = new HashSet<Partido>();
        }
    
        public int id { get; set; }
        public string nombre { get; set; }
        public Nullable<int> id_fundador { get; set; }
        public int id_distrito { get; set; }
    
        public virtual Distrito Distrito { get; set; }
        public virtual Persona Persona { get; set; }
        public virtual ICollection<Equipos_x_Campeonato> Equipos_x_Campeonato { get; set; }
        public virtual ICollection<Jugadore> Jugadores { get; set; }
        public virtual ICollection<Partido> Partidos { get; set; }
        public virtual ICollection<Partido> Partidos1 { get; set; }
    }
}
