//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto.Modelos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Eventos_x_Partido
    {
        public int id { get; set; }
        public int id_jugador { get; set; }
        public int id_partido { get; set; }
        public int id_evento { get; set; }
        public int minuto_evento { get; set; }
    
        public virtual Evento Evento { get; set; }
        public virtual Jugadore Jugadore { get; set; }
        public virtual Partido Partido { get; set; }
    }
}
