//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto.Modelos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Eventos_x_Partido
    {
        public int id { get; set; }
        public int id_jugador { get; set; }
        public int id_partido { get; set; }
        public int id_evento { get; set; }
        public int minuto_evento { get; set; }
    
        public virtual Evento Evento { get; set; }
        public virtual Jugadore Jugadore { get; set; }
        public virtual Partido Partido { get; set; }
    }
}
