//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto.Modelos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Evento
    {
        public Evento()
        {
            this.Eventos_x_Partido = new HashSet<Eventos_x_Partido>();
        }
    
        public int id { get; set; }
        public string nombre_evento { get; set; }
        public string descripcion { get; set; }
    
        public virtual ICollection<Eventos_x_Partido> Eventos_x_Partido { get; set; }
    }
}
