//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto.Modelos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Evento
    {
        public Evento()
        {
            this.Eventos_x_Partido = new HashSet<Eventos_x_Partido>();
        }
    
        public int id { get; set; }
        public string nombre_evento { get; set; }
        public string descripcion { get; set; }
    
        public virtual ICollection<Eventos_x_Partido> Eventos_x_Partido { get; set; }
    }
}
