//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto.Modelos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Jugadore
    {
        public Jugadore()
        {
            this.Eventos_x_Partido = new HashSet<Eventos_x_Partido>();
        }
    
        public int id { get; set; }
        public int id_persona { get; set; }
        public int id_equipo { get; set; }
        public int id_posicion { get; set; }
    
        public virtual Equipos Equipos { get; set; }
        public virtual ICollection<Eventos_x_Partido> Eventos_x_Partido { get; set; }
        public virtual Persona Persona { get; set; }
        public virtual Posicione Posicione { get; set; }
    }
}
