//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto.Modelos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Posicione
    {
        public Posicione()
        {
            this.Jugadores = new HashSet<Jugadore>();
        }
    
        public int id { get; set; }
        public string nombre { get; set; }
        public string codigo_posicion { get; set; }
    
        public virtual ICollection<Jugadore> Jugadores { get; set; }
    }
}
