//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto.Modelos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Posicione
    {
        public Posicione()
        {
            this.Jugadores = new HashSet<Jugadore>();
        }
    
        public int id { get; set; }
        public string nombre { get; set; }
        public string codigo_posicion { get; set; }
    
        public virtual ICollection<Jugadore> Jugadores { get; set; }
    }
}
