//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto.Modelos
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class progra5Entities : DbContext
    {
        public progra5Entities()
            : base("name=progra5Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Campeonato> Campeonatos { get; set; }
        public DbSet<Cantone> Cantones { get; set; }
        public DbSet<Distrito> Distritos { get; set; }
        public DbSet<Equipos> Equipos { get; set; }
        public DbSet<Equipos_x_Campeonato> Equipos_x_Campeonato { get; set; }
        public DbSet<Evento> Eventos { get; set; }
        public DbSet<Eventos_x_Partido> Eventos_x_Partido { get; set; }
        public DbSet<Jugadore> Jugadores { get; set; }
        public DbSet<Partido> Partidos { get; set; }
        public DbSet<Persona> Personas { get; set; }
        public DbSet<Posicione> Posiciones { get; set; }
        public DbSet<Provincia> Provincias { get; set; }
        public DbSet<sysdiagram> sysdiagrams { get; set; }
        public DbSet<Usuario> Usuarios { get; set; }
    }
}
