//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto.Modelos
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class ProyectoBD : DbContext
    {
        public ProyectoBD()
            : base("name=ProyectoBD")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Campeonato> Campeonatos { get; set; }
        public DbSet<Cantone> Cantones { get; set; }
        public DbSet<Distrito> Distritos { get; set; }
        public DbSet<Equipos> Equipos { get; set; }
        public DbSet<Equipos_x_Campeonato> Equipos_x_Campeonato { get; set; }
        public DbSet<Evento> Eventos { get; set; }
        public DbSet<Eventos_x_Partido> Eventos_x_Partido { get; set; }
        public DbSet<Jugadore> Jugadores { get; set; }
        public DbSet<Partido> Partidos { get; set; }
        public DbSet<Persona> Personas { get; set; }
        public DbSet<Posicione> Posiciones { get; set; }
        public DbSet<Provincia> Provincias { get; set; }
        public DbSet<Usuario> Usuarios { get; set; }
        public DbSet<sysdiagram> sysdiagrams { get; set; }
    
        public virtual int sp_EliminaCanton(Nullable<int> id_canton)
        {
            var id_cantonParameter = id_canton.HasValue ?
                new ObjectParameter("id_canton", id_canton) :
                new ObjectParameter("id_canton", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_EliminaCanton", id_cantonParameter);
        }
    
        public virtual int sp_InsertaCanton(Nullable<int> id_provincia, string nombre, Nullable<int> id_canton_inec)
        {
            var id_provinciaParameter = id_provincia.HasValue ?
                new ObjectParameter("id_provincia", id_provincia) :
                new ObjectParameter("id_provincia", typeof(int));
    
            var nombreParameter = nombre != null ?
                new ObjectParameter("nombre", nombre) :
                new ObjectParameter("nombre", typeof(string));
    
            var id_canton_inecParameter = id_canton_inec.HasValue ?
                new ObjectParameter("id_canton_inec", id_canton_inec) :
                new ObjectParameter("id_canton_inec", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_InsertaCanton", id_provinciaParameter, nombreParameter, id_canton_inecParameter);
        }
    
        public virtual int sp_ModificaCanton(Nullable<int> id_canton, Nullable<int> id_provincia, string nombre, Nullable<int> id_canton_inec)
        {
            var id_cantonParameter = id_canton.HasValue ?
                new ObjectParameter("id_canton", id_canton) :
                new ObjectParameter("id_canton", typeof(int));
    
            var id_provinciaParameter = id_provincia.HasValue ?
                new ObjectParameter("id_provincia", id_provincia) :
                new ObjectParameter("id_provincia", typeof(int));
    
            var nombreParameter = nombre != null ?
                new ObjectParameter("nombre", nombre) :
                new ObjectParameter("nombre", typeof(string));
    
            var id_canton_inecParameter = id_canton_inec.HasValue ?
                new ObjectParameter("id_canton_inec", id_canton_inec) :
                new ObjectParameter("id_canton_inec", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_ModificaCanton", id_cantonParameter, id_provinciaParameter, nombreParameter, id_canton_inecParameter);
        }
    
        public virtual ObjectResult<sp_RetornaCantones_Result> sp_RetornaCantones(string nombre, Nullable<int> id_provincia)
        {
            var nombreParameter = nombre != null ?
                new ObjectParameter("nombre", nombre) :
                new ObjectParameter("nombre", typeof(string));
    
            var id_provinciaParameter = id_provincia.HasValue ?
                new ObjectParameter("id_provincia", id_provincia) :
                new ObjectParameter("id_provincia", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_RetornaCantones_Result>("sp_RetornaCantones", nombreParameter, id_provinciaParameter);
        }
    
        public virtual ObjectResult<sp_RetornaCantonesid_canton_Result> sp_RetornaCantonesid_canton(Nullable<int> id_canton)
        {
            var id_cantonParameter = id_canton.HasValue ?
                new ObjectParameter("id_canton", id_canton) :
                new ObjectParameter("id_canton", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_RetornaCantonesid_canton_Result>("sp_RetornaCantonesid_canton", id_cantonParameter);
        }
    
        public virtual ObjectResult<sp_RetornaDistritos_Result> sp_RetornaDistritos(string nombre, Nullable<int> id_canton)
        {
            var nombreParameter = nombre != null ?
                new ObjectParameter("nombre", nombre) :
                new ObjectParameter("nombre", typeof(string));
    
            var id_cantonParameter = id_canton.HasValue ?
                new ObjectParameter("id_canton", id_canton) :
                new ObjectParameter("id_canton", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_RetornaDistritos_Result>("sp_RetornaDistritos", nombreParameter, id_cantonParameter);
        }
    
        public virtual ObjectResult<sp_RetornaProvincias_Result> sp_RetornaProvincias(string nombre, Nullable<int> id_provincia)
        {
            var nombreParameter = nombre != null ?
                new ObjectParameter("nombre", nombre) :
                new ObjectParameter("nombre", typeof(string));
    
            var id_provinciaParameter = id_provincia.HasValue ?
                new ObjectParameter("id_provincia", id_provincia) :
                new ObjectParameter("id_provincia", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_RetornaProvincias_Result>("sp_RetornaProvincias", nombreParameter, id_provinciaParameter);
        }
    
        public virtual ObjectResult<sp_RetornaUsuario_Result> sp_RetornaUsuario(string nombre_usuario, Nullable<int> id_Usuario)
        {
            var nombre_usuarioParameter = nombre_usuario != null ?
                new ObjectParameter("nombre_usuario", nombre_usuario) :
                new ObjectParameter("nombre_usuario", typeof(string));
    
            var id_UsuarioParameter = id_Usuario.HasValue ?
                new ObjectParameter("id_Usuario", id_Usuario) :
                new ObjectParameter("id_Usuario", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_RetornaUsuario_Result>("sp_RetornaUsuario", nombre_usuarioParameter, id_UsuarioParameter);
        }
    
        public virtual ObjectResult<sp_RetornaUsuarioID_Result> sp_RetornaUsuarioID(Nullable<int> id_usuario)
        {
            var id_usuarioParameter = id_usuario.HasValue ?
                new ObjectParameter("id_usuario", id_usuario) :
                new ObjectParameter("id_usuario", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_RetornaUsuarioID_Result>("sp_RetornaUsuarioID", id_usuarioParameter);
        }
    
        public virtual ObjectResult<sp_RetornaUsuarioNombrePwd_Result> sp_RetornaUsuarioNombrePwd(string nombre_usuario, string contrasena)
        {
            var nombre_usuarioParameter = nombre_usuario != null ?
                new ObjectParameter("nombre_usuario", nombre_usuario) :
                new ObjectParameter("nombre_usuario", typeof(string));
    
            var contrasenaParameter = contrasena != null ?
                new ObjectParameter("contrasena", contrasena) :
                new ObjectParameter("contrasena", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_RetornaUsuarioNombrePwd_Result>("sp_RetornaUsuarioNombrePwd", nombre_usuarioParameter, contrasenaParameter);
        }
    
        public virtual int PA_OBTENER_INDEX_TABLE(string nombreTabla, string nombreIdentificador)
        {
            var nombreTablaParameter = nombreTabla != null ?
                new ObjectParameter("nombreTabla", nombreTabla) :
                new ObjectParameter("nombreTabla", typeof(string));
    
            var nombreIdentificadorParameter = nombreIdentificador != null ?
                new ObjectParameter("nombreIdentificador", nombreIdentificador) :
                new ObjectParameter("nombreIdentificador", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PA_OBTENER_INDEX_TABLE", nombreTablaParameter, nombreIdentificadorParameter);
        }
    
        public virtual ObjectResult<pa_obtener_lista_personas_Result> pa_obtener_lista_personas(string identificacion)
        {
            var identificacionParameter = identificacion != null ?
                new ObjectParameter("identificacion", identificacion) :
                new ObjectParameter("identificacion", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pa_obtener_lista_personas_Result>("pa_obtener_lista_personas", identificacionParameter);
        }
    
        public virtual int PA_OBTENER_SIG_INDEX(string nombreTabla, string nombreIdentificador)
        {
            var nombreTablaParameter = nombreTabla != null ?
                new ObjectParameter("nombreTabla", nombreTabla) :
                new ObjectParameter("nombreTabla", typeof(string));
    
            var nombreIdentificadorParameter = nombreIdentificador != null ?
                new ObjectParameter("nombreIdentificador", nombreIdentificador) :
                new ObjectParameter("nombreIdentificador", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PA_OBTENER_SIG_INDEX", nombreTablaParameter, nombreIdentificadorParameter);
        }
    
        public virtual int pa_Progra5Delete1(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("pa_Progra5Delete1", idParameter);
        }
    
        public virtual int pa_Progra5Delete2(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("pa_Progra5Delete2", idParameter);
        }
    
        public virtual int pa_Progra5Insert1(Nullable<int> id, string nombre, string usuario_Creacion, Nullable<System.DateTime> fecha_Creacion, string usuario_Modificacion, Nullable<System.DateTime> fecha_Ult_Mod, string vc_Estado)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            var nombreParameter = nombre != null ?
                new ObjectParameter("Nombre", nombre) :
                new ObjectParameter("Nombre", typeof(string));
    
            var usuario_CreacionParameter = usuario_Creacion != null ?
                new ObjectParameter("Usuario_Creacion", usuario_Creacion) :
                new ObjectParameter("Usuario_Creacion", typeof(string));
    
            var fecha_CreacionParameter = fecha_Creacion.HasValue ?
                new ObjectParameter("Fecha_Creacion", fecha_Creacion) :
                new ObjectParameter("Fecha_Creacion", typeof(System.DateTime));
    
            var usuario_ModificacionParameter = usuario_Modificacion != null ?
                new ObjectParameter("Usuario_Modificacion", usuario_Modificacion) :
                new ObjectParameter("Usuario_Modificacion", typeof(string));
    
            var fecha_Ult_ModParameter = fecha_Ult_Mod.HasValue ?
                new ObjectParameter("Fecha_Ult_Mod", fecha_Ult_Mod) :
                new ObjectParameter("Fecha_Ult_Mod", typeof(System.DateTime));
    
            var vc_EstadoParameter = vc_Estado != null ?
                new ObjectParameter("Vc_Estado", vc_Estado) :
                new ObjectParameter("Vc_Estado", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("pa_Progra5Insert1", idParameter, nombreParameter, usuario_CreacionParameter, fecha_CreacionParameter, usuario_ModificacionParameter, fecha_Ult_ModParameter, vc_EstadoParameter);
        }
    
        public virtual int pa_Progra5Insert2(Nullable<int> id, string nombre_Evento, string descripcion)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            var nombre_EventoParameter = nombre_Evento != null ?
                new ObjectParameter("Nombre_Evento", nombre_Evento) :
                new ObjectParameter("Nombre_Evento", typeof(string));
    
            var descripcionParameter = descripcion != null ?
                new ObjectParameter("Descripcion", descripcion) :
                new ObjectParameter("Descripcion", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("pa_Progra5Insert2", idParameter, nombre_EventoParameter, descripcionParameter);
        }
    
        public virtual ObjectResult<pa_Progra5Select1_Result> pa_Progra5Select1()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pa_Progra5Select1_Result>("pa_Progra5Select1");
        }
    
        public virtual ObjectResult<pa_Progra5Select2_Result> pa_Progra5Select2()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pa_Progra5Select2_Result>("pa_Progra5Select2");
        }
    
        public virtual int pa_Progra5Update1(Nullable<int> id, string nombre, Nullable<int> id_Fundador, Nullable<int> id_Distrito)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            var nombreParameter = nombre != null ?
                new ObjectParameter("Nombre", nombre) :
                new ObjectParameter("Nombre", typeof(string));
    
            var id_FundadorParameter = id_Fundador.HasValue ?
                new ObjectParameter("Id_Fundador", id_Fundador) :
                new ObjectParameter("Id_Fundador", typeof(int));
    
            var id_DistritoParameter = id_Distrito.HasValue ?
                new ObjectParameter("Id_Distrito", id_Distrito) :
                new ObjectParameter("Id_Distrito", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("pa_Progra5Update1", idParameter, nombreParameter, id_FundadorParameter, id_DistritoParameter);
        }
    
        public virtual int pa_Progra5Update2(Nullable<int> id, Nullable<System.DateTime> fec_Inicio, Nullable<System.DateTime> fec_Fin, Nullable<int> cant_Equipos, Nullable<int> id_Dedicado)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            var fec_InicioParameter = fec_Inicio.HasValue ?
                new ObjectParameter("Fec_Inicio", fec_Inicio) :
                new ObjectParameter("Fec_Inicio", typeof(System.DateTime));
    
            var fec_FinParameter = fec_Fin.HasValue ?
                new ObjectParameter("Fec_Fin", fec_Fin) :
                new ObjectParameter("Fec_Fin", typeof(System.DateTime));
    
            var cant_EquiposParameter = cant_Equipos.HasValue ?
                new ObjectParameter("Cant_Equipos", cant_Equipos) :
                new ObjectParameter("Cant_Equipos", typeof(int));
    
            var id_DedicadoParameter = id_Dedicado.HasValue ?
                new ObjectParameter("Id_Dedicado", id_Dedicado) :
                new ObjectParameter("Id_Dedicado", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("pa_Progra5Update2", idParameter, fec_InicioParameter, fec_FinParameter, cant_EquiposParameter, id_DedicadoParameter);
        }
    
        public virtual int sp_alterdiagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_alterdiagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_creatediagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_creatediagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_dropdiagram(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_dropdiagram", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagramdefinition_Result> sp_helpdiagramdefinition(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagramdefinition_Result>("sp_helpdiagramdefinition", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagrams_Result> sp_helpdiagrams(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagrams_Result>("sp_helpdiagrams", diagramnameParameter, owner_idParameter);
        }
    
        public virtual int sp_renamediagram(string diagramname, Nullable<int> owner_id, string new_diagramname)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var new_diagramnameParameter = new_diagramname != null ?
                new ObjectParameter("new_diagramname", new_diagramname) :
                new ObjectParameter("new_diagramname", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_renamediagram", diagramnameParameter, owner_idParameter, new_diagramnameParameter);
        }
    
        public virtual int sp_upgraddiagrams()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_upgraddiagrams");
        }
    
        public virtual ObjectResult<pa_obtener_lista_usuarios_Result> pa_obtener_lista_usuarios(string identificacion)
        {
            var identificacionParameter = identificacion != null ?
                new ObjectParameter("identificacion", identificacion) :
                new ObjectParameter("identificacion", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pa_obtener_lista_usuarios_Result>("pa_obtener_lista_usuarios", identificacionParameter);
        }
    
        public virtual int UPDATE_ULTIMO_INGRESO(Nullable<System.DateTime> ult_date, Nullable<int> id)
        {
            var ult_dateParameter = ult_date.HasValue ?
                new ObjectParameter("ult_date", ult_date) :
                new ObjectParameter("ult_date", typeof(System.DateTime));
    
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UPDATE_ULTIMO_INGRESO", ult_dateParameter, idParameter);
        }
    
        public virtual ObjectResult<pa_obtener_partidos_torneo_Result> pa_obtener_partidos_torneo(Nullable<int> id_torneo)
        {
            var id_torneoParameter = id_torneo.HasValue ?
                new ObjectParameter("id_torneo", id_torneo) :
                new ObjectParameter("id_torneo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pa_obtener_partidos_torneo_Result>("pa_obtener_partidos_torneo", id_torneoParameter);
        }
    
        public virtual ObjectResult<pa_partidos_torneo_Result> pa_partidos_torneo(Nullable<int> id_torneo)
        {
            var id_torneoParameter = id_torneo.HasValue ?
                new ObjectParameter("id_torneo", id_torneo) :
                new ObjectParameter("id_torneo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pa_partidos_torneo_Result>("pa_partidos_torneo", id_torneoParameter);
        }
    }
}
